### ISSUE TITLE
Missing pull rate data for Surging Sparks

### ISSUE THREAD

**Issue by aprct** [Pepper0ni/TTS-PTCG-Pack-Simulator#12]
As always, I'm a huge fan of your work. :)

It looks like https://github.com/Pepper0ni/TTS-PTCG-Pack-Simulator/wiki/Pull-rate-and-card-order-Information is missing the Surging Sparks data used in the Steam Workshop item.

If there's anything I can do to support your work, then please let me know!

**Comment by Pepper0ni** [comment]
Sorry for the delay, I've been suffering from both PTCG burnout and coder burnout from another project lately which combined with TCGPlayer being slower than usual this set to release their article made it slip from my priority list. 

As for assistance, there are a couple of half finished things I have lying around that could be patched up with a bit of motivation and lua knowledge, specifically a WIP theme deck selector, a final look over the decklist loader before I find the energy to make it an official feature, and changing the card search to use reg mark to determine what's in standard instead of trusting the API which has never updated it.

I have noticed a spike in downloads and general activity in TTS PTCG lately now the romyking mod has a successor, but I'm not attached to whatever thier community as is. If you happened to know anything about that it could end up working out for everyone.

EDIT: otherwise, if you want to help with updates, send me a message/email somehow a week before the next set releases, that's when the work starts.

**Comment by aprct** [comment]
Happy to discuss further. How do I contact you?

**Comment by Pepper0ni** [comment]
I'm fine with either steam (Pepper0ni , if you somehow can't find me from
the mod page), email ( pepper0ni3steps @ gmail .com) or discord (pepper0ni),
unless you have anything specific in mind.
